### PR TITLE
Added a Blacklist to the Dolly.

### LINKED ISSUE #8838: Dolly works on nuke chambers - they shouldn’t.
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.1.1.0

### Your Proposal

The regular dolly will pick up a nuke chamber

### Your Goal

I had one in my hot bar and accidentally picked up a nuke chamber, spilling its contents. 

Luckily it was off and didn’t meltdown. 

### Your Vision

Dollies shouldn’t move nuke chambers. Moving molecular transformers is ok I guess. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

### PR DESCRIPTION
**Pull request by draknyte1**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8838

### CODE REVIEW

**Comment by bombcar** [comment]
Will this need an actual line added to the config for the nuke chambers?

**Comment by draknyte1** [comment]
> Will this need an actual line added to the config for the nuke chambers?

Yes, along with anything else that should be blacklisted.

**Comment by bombcar** [comment]
I can make a proposed blacklist - the Nuke Chamber is:

image

what would be an example config line?

`BlacklistedTileEntiyClassNames=IC2:blockReactorChamber`

**Comment by draknyte1** [comment]
> what would be an example config line?

It’s the full name of the tile entity class.

**Comment by bombcar** [comment]
Now to find out what that is 😂

**Comment by bombcar** [comment]
ready to go with 

```
    # The Canonical Class-Names of TileEntities that should be ignored when using a Dolly.
    S:BlacklistedTileEntiyClassNames <
        ic2.core.block.machine.tileentity.TileEntityNuke
    >
```

for the config

**Pull request merged**
