### PR TITLE
Fix voiding

### LINKED ISSUE #10211: GT Auto-Output Voids into JABBA Barrel
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

Kevlar Test Pack

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Output GT machine into barrel. Expect to fill up to 64 x 64 and machine to buffer.

### The Reality

Output from GT machine into barrel stops at 63 x 64 + 1. Machine continues to run but barrel never fills up past 63 x 64 + 1.

image

image

### Your Proposal

Fix?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by kuba6000**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10211
~~Still voids 1 item~~ It is a bit weird, but seems to be working fine

### CODE REVIEW

**Comment by MuXiu1997** [comment]
I'm curious as to why this is working fine

**Comment by MuXiu1997** [comment]
I got it
```java
for (int i = 0; i < tPutInventory.getSizeInventory(); i++) {
                int slot = i;
                if(accessibleSlots != null)
                {
                    if(accessibleSlots.length <= i)
                        break;
                    slot = accessibleSlots[slot];
                }
                ItemStack s = tPutInventory.getStackInSlot(slot);
                if(s == null) {
                    tPutFreeSlots.add(slot);
                } else if((s.stackSize < s.getMaxStackSize() && s.stackSize < tPutInventory.getInventoryStackLimit()) && aMinMoveAtOnce <= s.getMaxStackSize() - s.stackSize) {
                    ItemId sID = ItemId.createNoCopy(s);
                    tPutItems.merge(sID, (Math.min(s.getMaxStackSize(), tPutInventory.getInventoryStackLimit()) - s.stackSize), Integer::sum);
                    tPutItemStacks.computeIfAbsent(sID, k -> new ArrayList<>()).add(s);
                }
            }
```
`StorageLocal#getStackInSlot` will trigger `StorageLocal#markDirty`
so `tPutItemStacks.get(sID).get(0)` was no longer `IBarrelStorage. inputStack`
Why not call `tPutInventory#setInventorySlotContents` once more?

**Comment by kuba6000** [comment]
> I got it
> ```java
> for (int i = 0; i < tPutInventory.getSizeInventory(); i++) {
>                 int slot = i;
>                 if(accessibleSlots != null)
>                 {
>                     if(accessibleSlots.length <= i)
>                         break;
>                     slot = accessibleSlots[slot];
>                 }
>                 ItemStack s = tPutInventory.getStackInSlot(slot);
>                 if(s == null) {
>                     tPutFreeSlots.add(slot);
>                 } else if((s.stackSize < s.getMaxStackSize() && s.stackSize < tPutInventory.getInventoryStackLimit()) && aMinMoveAtOnce <= s.getMaxStackSize() - s.stackSize) {
>                     ItemId sID = ItemId.createNoCopy(s);
>                     tPutItems.merge(sID, (Math.min(s.getMaxStackSize(), tPutInventory.getInventoryStackLimit()) - s.stackSize), Integer::sum);
>                     tPutItemStacks.computeIfAbsent(sID, k -> new ArrayList<>()).add(s);
>                 }
>             }
> ```
> `StorageLocal#getStackInSlot` will trigger `StorageLocal#markDirty`
> so `tPutItemStacks.get(sID).get(0)` was no longer `IBarrelStorage. inputStack`
> Why not call `tPutInventory#setInventorySlotContents` once more?

Well, when you call getStackInSlot then the stack you get should stay in that slot. Setting the same stack in the same slot is inlogical and should not be done in my opinion.

**Comment by MuXiu1997** [comment]
~~Another idea I had was to make jabba not call markDirty when getStackInSlot~~

**Comment by MuXiu1997** [comment]
The current solution is too weird
Maybe I don't have a better suggestion either

**Review by MuXiu1997 — APPROVED** [review]

**Pull request merged**
